name: Test Discord Webhook Notification

on:
  workflow_dispatch:  # 手動で実行できるように設定

jobs:
  test-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Check and Send Test Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_WEBHOOK_CODE: ${{ secrets.DISCORD_WEBHOOK_CODE }}
        run: |
          if [ -z "$DISCORD_WEBHOOK_URL" ] || [ -z "$DISCORD_WEBHOOK_CODE" ]; then
            echo "Error: One or both secrets are missing."
            exit 1
          fi

          echo "Sending test notification to $DISCORD_WEBHOOK_URL"
          
          curl -X POST "$DISCORD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg code "$DISCORD_WEBHOOK_CODE" \
                         '{code: $code, message: "🚀 Test notification from GitHub Actions."}')"
