name: Test Discord Webhook Secrets

on:
  workflow_dispatch:  # 手動実行でテストできるように設定

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Discord Webhook URL and Code
        run: |
          echo "Webhook URL Last 3 Characters: ${${{ secrets.DISCORD_WEBHOOK_URL }}: -3}"
